export const USER_ACTION_TYPES = {

    USER_LOGIN_START: 'USER_LOGIN_START',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

    USER_REGISTER_START: 'USER_REGISTER_START',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',

    USER_LOGOUT_START: 'USER_LOGOUT_START',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILED: 'USER_LOGOUT_FAILED',

    USER_UPDATE_START: 'USER_UPDATE_START',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',

    GET_CURRENT_USER_START: "GET_CURRENT_USER_START",
    GET_CURRENT_USER_SUCCESS: "GET_CURRENT_USER_SUCCESS",
    GET_CURRENT_USER_FAILED: "GET_CURRENT_USER_FAILED",

    TOGGLE_SIDEBAR:"TOGGLE_SIDEBAR"
    
}

