export const JOBS_ACTION_TYPES = {
    GET_JOBS_START: 'GET_JOBS_START',
    GET_JOBS_SUCCESS: 'GET_JOBS_SUCCESS',
    GET_JOBS_FAILED: 'GET_JOBS_FAILED',

    UPDATE_FILTER: "UPDATE_FILTER",
    CLEAR_FILTER: "CLEAR_FILTER"
}

