export const JOB_ACTION_TYPES = {

    CREATE_JOB_START: 'CREATE_JOB_START',
    CREATE_JOB_SUCCESS: 'CREATE_JOB_SUCCESS',
    CREATE_JOB_FAILED: 'CREATE_JOB_FAILED',

    EDIT_JOB: 'EDIT_JOB',

    EDIT_JOB_START: 'EDIT_JOB_START',
    EDIT_JOB_SUCCESS: 'EDIT_JOB_SUCCESS',
    EDIT_JOB_FAILED: 'EDIT_JOB_FAILED',

    DELETE_JOB_START: 'DELETE_JOB_START',
    DELETE_JOB_SUCCESS: 'DELETE_JOB_SUCCESS',
    DELETE_JOB_FAILED: 'DELETE_JOB_FAILED',

    JOB_FIELD_CHANGE: "JOB_FIELD_CHANGE"

}

